[ids]
*

[main]
capslock = overload(esc_layer, esc)
leftalt = overload(symbols, leftalt)

[esc_layer]

[symbols]
j = (
k = )
u = [
i = ]
n = {
m = }
h = minus
l = equal
y = backslash
o = S-backslash
p = S-apostrophe
comma = apostrophe
