shell /usr/bin/zsh

# keymaps
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map ctrl+u        scroll_page_up
map ctrl+d        scroll_page_down
map ctrl+shift+c  copy_to_clipboard

# font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        12.0

# window
window_padding_width 8

# cursor
cursor_shape          beam
cursor_beam_thickness 1.5
cursor_blink_interval 0

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
